### ISSUE TITLE
Veeam Module crashes if both MsSql and PostgreSQL configs/dbs are present

### ISSUE THREAD

**Issue by bongobongoland** [mpgn/CrackMapExec#72]
<img width="1254" alt="rdokHK4" src="https://github.com/mpgn/CrackMapExec/assets/129246896/e880caf6-fd01-4956-b337-484d629029aa">

And here's what the module is dealing with:

```
[HKEY_LOCAL_MACHINE\SOFTWARE\Veeam\Veeam Backup and Replication\DatabaseConfigurations]
"SqlActiveConfiguration"="MsSql"

[HKEY_LOCAL_MACHINE\SOFTWARE\Veeam\Veeam Backup and Replication\DatabaseConfigurations\MsSql]
"SqlDatabaseName"="VeeamBackup"
"SqlInstanceName"="VEEAMSQL2016"
"SqlLockInfo"="<CLockInfo xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" Id=\"\" Time=\"\"><Computer>SOMESERVER</Computer><UserName>SOMESERVER\\Administrator</UserName></CLockInfo>"
"SqlLogin"=""
"SqlSecuredPassword"=""
"SqlServerName"="SOMESERVER"

[HKEY_LOCAL_MACHINE\SOFTWARE\Veeam\Veeam Backup and Replication\DatabaseConfigurations\PostgreSql]
"SqlDatabaseName"="VeeamBackup"
"SqlSecuredPassword"=""
"PostgresUserForWindowsAuth"="postgres"
"SqlHostName"="SOMESERVER"
"SqlHostPort"=dword:00001538
"SqlLockInfo"=""
"SqlUserName"=""
```
As you can see, both MsSql and PostgreSQL have the same hostname in the config and the same Database names.

The module successfully grabs the first two credits (out of 30) from MsSql and then crashes without showing the rest of the credentials. Doesn't touch postgresql. 

Hope that helps.

**Comment by NeffIsBack** [comment]
Thanks for the bug report. It's probably just an empty password which doesn't get handled properly when it gets formatted.

To the Postgres database, the module will only check the active database (SqlActiveCpnfiguration). I am pretty sure the other database is empty. 
This is because veeam changed the db from v11 to v12 from sql to Postgres, so older installations from v11 will use mssql while a fresh install will automatically use the new PostgreSQL.
